"""meta-scout: weekly codebase analysis that proposes feature ideas as GitHub issues."""

from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
from pathlib import Path

from pydantic import BaseModel, ConfigDict

log = logging.getLogger(__name__)

REPO = "haykharut/claude-p"

OUT_OF_SCOPE = """\
Docker runtime, Node runtime, bubblewrap sandbox, Telegram notifier, email
notifier, inbox/ file-triggered runs, shared-folder cross-job UI,
Syncthing setup docs, multi-user/RBAC, local image registry, proper agent
trace viewer (chat-style), per-job budget enforcement as a hard gate."""

LABELS = [
    ("scout-proposal", "0E8A16", "Proposed by meta-scout — awaiting review"),
    ("approved", "1D76DB", "Approved for meta-builder implementation"),
    ("in-progress", "FBCA04", "meta-builder is working on this"),
    ("builder-failed", "D93F0B", "meta-builder attempted but checks failed"),
]

PHASE1_PROMPT = f"""\
You are a senior software architect analyzing the claude-p codebase to generate
improvement ideas. claude-p is a home-server job runner for Claude Code agent
jobs, targeting solo hackers with a personal server and a Claude subscription.

## Before you generate anything

Write a 1–2 paragraph analysis of where this codebase is in its lifecycle, what
kind of user it serves, and what categories of improvement would matter most
right now. Ground this in what you actually see in the code and changelog — not
generalities. This analysis will frame your candidate generation.

## Exploration steps (do all of these before generating candidates)

1. Read README.md, CLAUDE.md, CHANGELOG.md (especially the [Unreleased] section)
2. Read docs/jobs.md and docs/overview.md if they exist
3. Read core source: src/claude_p/__init__.py, executor.py, scheduler.py,
   manifest.py, models.py, auto_schedule.py, config.py
4. Read the web layer: src/claude_p/api/*.py, src/claude_p/web/templates/*.html
5. Run: git log --oneline -50
6. Run: gh issue list --state all --limit 200 --repo {REPO}
7. Run: find src/claude_p -type f -name '*.py' | sort

## What makes a GOOD idea

- Fills a real gap visible in the code (missing error handling, missing feature
  that existing code scaffolds toward, UX papercut in the dashboard)
- Small enough for one developer (human or AI) to implement in 1–3 days
- Aligned with the project's philosophy: solo hacker, home server,
  subscription-based, lightweight
- Not already done (check CHANGELOG [Unreleased] and git log)
- Not already proposed (check existing GitHub issues)

## What is explicitly OUT OF SCOPE (do NOT propose these)

{OUT_OF_SCOPE}

## Output

Write a file called candidates.json in the current directory with this structure:

{{
  "generated_at": "<ISO datetime>",
  "lifecycle_analysis": "<your 1-2 paragraph analysis from above>",
  "candidates": [
    {{
      "id": 1,
      "title": "<concise title>",
      "description": "<2-3 sentences explaining the idea>",
      "category": "enhancement|feature|fix|dx|docs",
      "touches": ["<list of files/modules this would change>"],
      "rough_effort": "<hours or days estimate>"
    }}
  ]
}}

Generate 8–15 candidates. Be specific — reference actual file names, function
names, and line-level observations. Vague ideas like "improve error handling"
are useless unless you say WHERE and WHY.
"""

PHASE2_PROMPT = f"""\
You are a rigorous technical reviewer. Your job is to evaluate a set of feature
proposals for the claude-p project and select only the strongest ones.

## Input

Read the file candidates.json in the current directory. It contains raw ideas
generated by a brainstorming pass over the claude-p codebase.

## Evaluation criteria

Score each candidate on a 1–5 scale for each criterion:

1. **Value** (1–5): How much does this improve the project for its target user
   (solo hacker with a home server and Claude subscription)?
2. **Feasibility** (1–5): Can this be implemented correctly in 1–3 days by an
   AI coding agent working alone? Consider: complexity, testing difficulty,
   risk of regressions, clarity of acceptance criteria.
3. **Alignment** (1–5): Does this fit the project's philosophy? Lightweight,
   single-user, no heavy infra, subscription-based Claude usage, filesystem
   as the source of truth.
4. **Not-already-done** (pass/fail): Is this NOT already in CHANGELOG
   [Unreleased], NOT in existing GitHub issues, NOT a duplicate of another
   candidate in this batch?
5. **Not-out-of-scope** (pass/fail): Is this NOT in the explicit out-of-scope
   list below?

The out-of-scope list (reject any idea that overlaps with these):
{OUT_OF_SCOPE}

## Selection rules

- REJECT any candidate that fails "not-already-done" or "not-out-of-scope"
- REJECT any candidate with Value < 3 OR Feasibility < 3 OR Alignment < 3
- Compute composite_score = Value + Feasibility + Alignment (max 15)
- Keep the top 3–5 survivors ranked by composite_score
- If fewer than 3 survive, that is fine — quality over quantity

## Output format

Write a file called proposals.json in the current directory:

{{
  "generated_at": "<ISO datetime>",
  "proposals": [
    {{
      "title": "<GitHub issue title — imperative mood, concise>",
      "body": "<Full GitHub issue body in markdown. Sections: Problem, Proposed Solution, Files to Change, Acceptance Criteria>",
      "labels": ["scout-proposal", "enhancement"],
      "evaluation": {{
        "value": 4,
        "feasibility": 5,
        "alignment": 4,
        "composite_score": 13,
        "rationale": "<1-2 sentences on why this survived the filter>"
      }}
    }}
  ],
  "rejected": [
    {{
      "title": "<original candidate title>",
      "reason": "<specific reason for rejection>"
    }}
  ]
}}

Be ruthless. Every proposal becomes a real GitHub issue that a human reviews.
A short list of high-confidence proposals is far better than a long list of
maybes. If you are unsure about a candidate, reject it.
"""


# ---------------------------------------------------------------------------
# Pydantic models for proposals.json validation
# ---------------------------------------------------------------------------


class Evaluation(BaseModel):
    model_config = ConfigDict(extra="forbid")
    value: int
    feasibility: int
    alignment: int
    composite_score: int
    rationale: str


class Proposal(BaseModel):
    model_config = ConfigDict(extra="forbid")
    title: str
    body: str
    labels: list[str]
    evaluation: Evaluation


class Rejected(BaseModel):
    model_config = ConfigDict(extra="forbid")
    title: str
    reason: str


class ProposalsFile(BaseModel):
    model_config = ConfigDict(extra="forbid")
    generated_at: str
    proposals: list[Proposal]
    rejected: list[Rejected]


# ---------------------------------------------------------------------------
# Claude CLI helper
# ---------------------------------------------------------------------------


def run_claude(
    prompt: str,
    *,
    allowed_tools: list[str],
    max_turns: int,
    max_budget_usd: float,
    cwd: Path,
) -> dict:
    """Shell out to claude -p and return the parsed result envelope."""
    claude_cli = os.environ.get("CLAUDE_P_CLAUDE_CLI", "claude")
    argv = [
        claude_cli,
        "-p",
        "--output-format",
        "json",
        "--verbose",
        "--permission-mode",
        "dontAsk",
        "--allowedTools",
        ",".join(allowed_tools),
        "--max-budget-usd",
        f"{max_budget_usd:g}",
        "--max-turns",
        str(max_turns),
        prompt,
    ]
    result = subprocess.run(argv, capture_output=True, text=True, cwd=cwd)
    if result.returncode != 0:
        print(f"claude -p failed (exit {result.returncode})", file=sys.stderr)
        print(result.stderr[-3000:], file=sys.stderr)
        sys.exit(1)

    envelope = json.loads(result.stdout)
    cost = float(envelope.get("cost_usd") or envelope.get("total_cost_usd") or 0)
    turns = int(envelope.get("num_turns") or 0)
    is_error = bool(envelope.get("is_error"))
    print(f"  cost=${cost:.2f}, turns={turns}, error={is_error}")

    _report_to_ledger(envelope)
    return envelope


def _report_to_ledger(envelope: dict) -> None:
    run_id = os.environ.get("CLAUDE_P_RUN_ID")
    job_dir = os.environ.get("CLAUDE_P_JOB_DIR")
    if not run_id or not job_dir:
        return
    usage = envelope.get("usage") or {}
    if not isinstance(usage, dict):
        usage = {}
    record = {
        "cost_usd": float(envelope.get("cost_usd") or envelope.get("total_cost_usd") or 0),
        "input_tokens": int(usage.get("input_tokens") or 0),
        "output_tokens": int(usage.get("output_tokens") or 0),
        "cache_read_tokens": int(usage.get("cache_read_input_tokens") or 0),
        "cache_creation_tokens": int(usage.get("cache_creation_input_tokens") or 0),
        "num_turns": int(envelope.get("num_turns") or 0),
        "session_id": envelope.get("session_id"),
        "is_error": bool(envelope.get("is_error")),
        "model_usage": envelope.get("modelUsage"),
    }
    run_dir = Path(job_dir) / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    with (run_dir / "claude_calls.jsonl").open("a") as f:
        f.write(json.dumps(record) + "\n")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def ensure_labels() -> None:
    for name, color, description in LABELS:
        subprocess.run(
            [
                "gh",
                "label",
                "create",
                name,
                "--color",
                color,
                "--description",
                description,
                "--force",
                "--repo",
                REPO,
            ],
            capture_output=True,
        )


def title_tokens(title: str) -> set[str]:
    return set(title.lower().split())


def is_duplicate(new_title: str, existing_titles: list[str], threshold: float = 0.6) -> bool:
    new_tokens = title_tokens(new_title)
    if not new_tokens:
        return False
    for existing in existing_titles:
        existing_tokens = title_tokens(existing)
        if not existing_tokens:
            continue
        overlap = len(new_tokens & existing_tokens) / max(len(new_tokens), len(existing_tokens))
        if overlap > threshold:
            return True
    return False


def get_existing_issue_titles() -> list[str]:
    result = subprocess.run(
        [
            "gh",
            "issue",
            "list",
            "--state",
            "all",
            "--limit",
            "200",
            "--json",
            "title",
            "--repo",
            REPO,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return []
    return [i["title"] for i in json.loads(result.stdout)]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    workspace = Path(os.environ.get("CLAUDE_P_WORKSPACE_DIR", "."))

    print("=== meta-scout: ensuring labels ===")
    ensure_labels()

    # Phase 1: brainstorm
    print("=== Phase 1: brainstorm ===")
    run_claude(
        prompt=PHASE1_PROMPT,
        allowed_tools=["Read", "Write", "Bash"],
        max_turns=25,
        max_budget_usd=1.50,
        cwd=workspace,
    )

    candidates_path = workspace / "candidates.json"
    if not candidates_path.exists():
        print("Phase 1 did not produce candidates.json", file=sys.stderr)
        sys.exit(1)

    raw = json.loads(candidates_path.read_text())
    n_candidates = len(raw.get("candidates", []))
    print(f"Phase 1 produced {n_candidates} candidates")

    # Phase 2: evaluate
    print("=== Phase 2: evaluate ===")
    run_claude(
        prompt=PHASE2_PROMPT,
        allowed_tools=["Read", "Write"],
        max_turns=10,
        max_budget_usd=0.75,
        cwd=workspace,
    )

    proposals_path = workspace / "proposals.json"
    if not proposals_path.exists():
        print("Phase 2 did not produce proposals.json", file=sys.stderr)
        sys.exit(1)

    proposals = ProposalsFile.model_validate(json.loads(proposals_path.read_text()))
    print(f"Phase 2: {len(proposals.proposals)} proposals, {len(proposals.rejected)} rejected")

    # Dedup against existing issues
    existing_titles = get_existing_issue_titles()
    created = 0
    skipped_dedup = 0

    for p in proposals.proposals:
        if is_duplicate(p.title, existing_titles):
            print(f"  SKIP (duplicate): {p.title}")
            skipped_dedup += 1
            continue

        body = (
            p.body
            + f"\n\n---\n_Scout evaluation: {p.evaluation.composite_score}/15 "
            + f"(V:{p.evaluation.value} F:{p.evaluation.feasibility} "
            + f"A:{p.evaluation.alignment})_\n"
            + f"_Rationale: {p.evaluation.rationale}_"
        )

        label_args: list[str] = []
        for label in p.labels:
            label_args.extend(["--label", label])

        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                p.title,
                "--body",
                body,
                *label_args,
                "--repo",
                REPO,
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            print(f"  CREATED: {p.title} → {result.stdout.strip()}")
            existing_titles.append(p.title)
            created += 1
        else:
            print(f"  FAILED: {p.title}: {result.stderr}", file=sys.stderr)

    print(f"\n=== Done: {created} issues created, {skipped_dedup} skipped (dedup) ===")


if __name__ == "__main__":
    main()
